#!/usr/bin/env sh

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use project's Node version
if [ -f .nvmrc ]; then
  nvm use
fi

# Run checks
npm run format
npm run check-markdown
npm run test-pre-commit
